ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
# FROM docker.elastic.co/logstash/logstash:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

# docker hub version
FROM elastic/logstash:${ELK_VERSION}